name: Deploy to GitHub Pages

# Run workflow on every push to the main branch.
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Build project
        run: dotnet build SmiteCalc.csproj
          
      - name: Publish project
        run: dotnet publish SmiteCalc.csproj -c Release -o release --nologo
