name: Deploy to GitHub Pages

# Run workflow on every push to the main branch.
on:
  push:
    branches: [ main ]
  
  schedule:
    - cron: '30 12 1-7,15-21 * 2'
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Build project
        run: dotnet build SmiteTools/SmiteTools.csproj
          
      - name: Publish project
        run: dotnet publish SmiteTools/SmiteTools.csproj -c Release -o release --nologo
        
      - name: Change base-tag in index.html from / to SmiteTools
        run: sed -i 's/<base href="\/" \/>/<base href="\/SmiteTools\/" \/>/g' release/wwwroot/index.html

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Get the latest gods
        run: curl -X GET "https://hmason55.github.io/SmiteApi/gods/gods.json" -o release/wwwroot/data/gods.json
        
      - name: Get the latest items
        run: curl -X GET "https://hmason55.github.io/SmiteApi/items/items.json" -o release/wwwroot/data/items.json
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: site
          folder: release/wwwroot
